import os
import glob


def TimKiem(root_dir, ext):
    return glob.glob(os.path.join(
        root_dir, f'**/*{ext}'), recursive=True)


base_folder ="../../../baocao"
pictures="../../../baocao/pictures"

files = TimKiem(pictures, '.png')
files += TimKiem(pictures, '.jpg')

with open(os.path.join(pictures,"_pictures.md"), 'w') as markdown:
    for file in files:
        
        markdown.write(f"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
        markdown.write(f"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n")
        # markdown.write(f"![]({os.path.relpath(file, folder)})\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 1]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{100100100100}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.9]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{909090909090}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.8]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{808080808080}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.7]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{707070707070}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.6]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{606060606060}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.5]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{505050505050}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.4]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{404040404040}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.3]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{303030303030}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.2]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{202020202020}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.1]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{101010101010}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n")
        markdown.write(f"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
         
import pyautogui

pyautogui.hotkey('ctrl', 'k')
pyautogui.hotkey('ctrl', 'w')
pyautogui.hotkey('ctrl', 'shift', 'g')
pyautogui.hotkey('ctrl', '9')
pyautogui.hotkey('ctrl', 'j')