import os
import glob


def TimKiem(root_dir, ext):
    return glob.glob(os.path.join(
        root_dir, f'**/*{ext}'), recursive=True)


base_folder = os.path.join(os.getcwd(), "../../../baocao")
folder = os.path.join(base_folder, "pictures")

files = TimKiem(folder, '.png')
files += TimKiem(folder, '.jpg')

with open(os.path.join(folder,"_pictures.md"), 'w') as markdown:
    for file in files:
        markdown.write(f"========================================\n")
        # markdown.write(f"![]({os.path.relpath(file, folder)})\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 1]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.9]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.8]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.7]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.6]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.5]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.4]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.3]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.2]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"%\n")
        markdown.write(f"\n")
        markdown.write(f"\\begin{{figure}}[H]\n")
        markdown.write(f"\\centering\n")
        markdown.write("\\includegraphics[scale = 0.1]{"+f"{os.path.relpath(file, base_folder).replace('\\', '/')}"+"}\n")
        markdown.write("\\caption{vvn20206205}\n")
        markdown.write(f"\\end{{figure}}\n")
        markdown.write(f"\n")
        markdown.write(f"========================================\n")
         
import pyautogui

pyautogui.hotkey('ctrl', 'k')
pyautogui.hotkey('ctrl', 'w')
pyautogui.hotkey('ctrl', 'shift', 'g')
pyautogui.hotkey('ctrl', '9')
pyautogui.hotkey('ctrl', 'j')